trigger:
  branches:
    include:
    - master
    - test
    - develop

# no PR triggers
pr: none

resources:
- repo: self

variables:
  imageName: 'projectorigin/example-frontend'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    kubeCon: 'kubecon-eloprindelse-prod'
    tag: '$(Build.BuildId)'
    namespace: 'eloprindelse'
  ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
    kubeCon: 'test-kube-con'
    tag: '$(Build.BuildId)'
    namespace: 'test-project-origin'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    kubeCon: 'dev-kube-con'
    tag: 'dev.$(Build.BuildId)'
    namespace: 'dev-project-origin'

${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  pool: 
    name: eloprindelse-prod
${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
  pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: build_and_publish
  displayName: Build and publish
  jobs:  
  - job: docker_build_push
    displayName: Docker build and push
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: Dockerfile
        tags: |
          latest
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: dockerHub
        tags: |
          latest
          $(tag)
          
- stage: update_dev_cluster
  displayName: Update kubernetes
  jobs:  
  - job: push_to_cluster
    displayName: Push to Cluster
    steps:
      - task: HelmDeploy@0
        displayName: Helm upgrade
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: $(kubeCon)
          namespace: $(namespace)
          command: upgrade
          chartType: filepath
          chartPath: ./chart
          releaseName: example-frontend
          overrideValues: tag=$(tag)
          install: true
          waitForExecution: true
