trigger:
- master
- develop

resources:
- repo: self

variables:
  imageName: 'projectorigin/example-frontend'
  vmImageName: 'ubuntu-latest'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: '$(Build.BuildId)'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    tag: 'dev.$(Build.BuildId)'
  ${{ if eq(variables['Build.SourceBranchName'], 'merge') }}:
    tag: 'merge.$(Build.BuildId)'

stages:
- stage: build_and_publish
  displayName: Build and publish
  jobs:  
  - job: docker_build_push
    displayName: Docker build and push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: Dockerfile
        tags: |
          latest
          $(tag)
    - task: Docker@2
      condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: dockerHub
        tags: |
          latest
          $(tag)
          
- stage: update_dev_cluster
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: Update kubernetes
  variables:
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      kubeCon: 'test-kube-con'
      namespace: 'test-project-origin'
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      kubeCon: 'dev-kube-con'
      namespace: 'dev-project-origin'
  jobs:  
  - job: push_to_cluster
    displayName: Push to Cluster
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: HelmDeploy@0
        displayName: Helm upgrade
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: $(kubeCon)
          namespace: $(namespace)
          command: upgrade
          chartType: filepath
          chartPath: ./chart
          releaseName: example-frontend
          overrideValues: tag=$(tag)
          install: true
          waitForExecution: true
