
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-frontend-deployment
  template:
    metadata:
      labels:
        app: example-frontend-deployment
    spec:
      containers:
        - name: example-frontend-container
          image: projectorigin/example-frontend:{{ .Values.tag }}
          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: example-frontend-config
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "500m"
